config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do 
	 	root 'products#index'
    resources :products, only: [:show]
    resources :categories, only: [:show]
		devise_for :users
  end
  namespace :admin do
    root 'products#index'
    resources :products
    resources :categories
  end
  match "*path", to: redirect("/#{I18n.default_locale}/%{path}"), via: :all
  match "", to: redirect("/#{I18n.default_locale}/"), via: :all
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name_en, presence: true, length: {maximum: 250}
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ProductImageUploader
  belongs_to :category

  validates :title_en, presence: true,
            length: { maximum: 250 }

  validates :price, presence: true,
            numericality: { greater_than_or_equal_to: 0.01 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  validates :name, presence: true

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def destroy
    Category.destroy(params[:id])

    redirect_to admin_categories_path
  end

  def category_params
    params.require(:category).permit(:name_en, :name_ru)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, @product]
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to [:admin, @product]
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.destroy(params[:id])
    redirect_to admin_products_url
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:title_en, :title_ru, :description_en, :description_ru, :price, :category_id, :image)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!, :admin_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :avatar
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :avatar
  end

  def admin_user
    unless current_user.admin?
      flash[:danger] = "You don't have enough permissions"
      redirect_to root_url
    end
  end

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.paginate(page: params[:page], per_page: 10)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_image(id)
    if File.exists? Rails.root.join('public', 'uploads', id.to_s)
      "/uploads/#{id}"
    else
      'coming-soon.png'
    end
  end
end

app/views/admin/categories/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1><%= t ".categories" %> <%= link_to 'Add category', new_admin_category_path, class: 'btn btn-success' %></h1>
  </div>
</div>

<hr />

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th style="width: 100px;">Actions</th>
  </tr>

  <% @categories.each do |category| %>
      <tr>
        <td><%= category.name_en %></td>
        <td>
          <%= link_to 'Delete', admin_category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
      </tr>
  <% end %>
</table>
<table class="table table-striped">
  <tr>
    <th>Название</th>
    <th style="width: 100px;">Действия</th>
  </tr>

  <% @categories.each do |category| %>
      <tr>
        <td><%= category.name_ru %></td>
        <td>
          <%= link_to 'Удалить', admin_category_path(category), method: :delete, data: {confirm: 'Вы уверены?'} %>
        </td>
      </tr>
  <% end %>
</table>

app/views/admin/categories/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Category</h1>
  </div>
</div>

<hr />

<%= form_for [:admin, @category], html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @category.errors[:name_en].any? %>">
      <%= f.label :name_en, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name_en, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @category, field_name: :name_en %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @category.errors[:name_ru].any? %>">
      <%= f.label :name_ru, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name_ru, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @category, field_name: :name_ru %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @product.errors[:title_en].any? %>">
      <%= f.label :title_en, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title_en, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :title_en %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:title_ru].any? %>">
      <%= f.label :title_ru, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title_ru, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :title_ru %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:description_en].any? %>">
      <%= f.label :description_en, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :description_en, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :description_en %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:description_ru].any? %>">
      <%= f.label :description_ru, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :description_ru, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :description_ru %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:price].any? %>">
      <%= f.label :price, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :price, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :price %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:category_id].any? %>">
      <%= f.label :category_id, 'Category', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select :category_id, Category.all, :id, :name_en, {}, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :category_id %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:image].any? %>">
      <%= f.label :image, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.file_field :image %>
        <%= render 'shared/field_errors', object: @product, field_name: :image %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Edit Product</h1>
  </div>
</div>

<hr />

<%= render 'form' %>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Products <%= link_to 'New Product', new_admin_product_path, class: 'btn btn-success' %></h1>
  </div>
</div>

<hr />

<table class="table table-striped">
  <tr>
    <th>Image</th>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th>Category</th>
    <th>Actions</th>
  </tr>

  <% @products.each do |product| %>
      <tr>
        <td><%= image_tag product.image.url(:medium) %></td>
        <td><%= product.title_en %></td>
        <td><%= product.description_en %></td>
        <td><%= product.price %></td>
        <td><%= product.category.name_en %></td>
        <td>
          <%= link_to 'View', admin_product_path(product) %>
          <%= link_to 'Edit', edit_admin_product_path(product) %>
          <%= link_to 'Delete', admin_product_path(product),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this product?'} %>
        </td>
      </tr>
  <% end %>

</table>

<table class="table table-striped">
  <tr>
    <th>Картинка</th>
    <th>Название</th>
    <th>Описание</th>
    <th>Цена</th>
    <th>Категория</th>
    <th>Действия</th>
  </tr>

  <% @products.each do |product| %>
      <tr>
        <td><%= image_tag product.image.url(:medium) %></td>
        <td><%= product.title_ru %></td>
        <td><%= product.description_ru %></td>
        <td><%= product.price %></td>
        <td><%= product.category.name_ru %></td>
        <td>
          <%= link_to 'Просмотр', admin_product_path(product) %>
          <%= link_to 'Редактировать', edit_admin_product_path(product) %>
          <%= link_to 'Удалить', admin_product_path(product),
                      method: :delete,
                      data: {confirm: 'Вы уверены?'} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/admin/products/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Product</h1>
  </div>
</div>

<hr />

<%= render 'form' %>

app/views/admin/products/show.html.erb
<h1><%= @product.title_en %> | <%= @product.title_ru %></h1>
<p><%= @product.description_en %></p>
<p><%= @product.description_ru %></p>
<p>
    Price: <b><%= @product.price %></b>
</p>
<p>
    <b>Category: </b> <%= @product.category.name_en %> | <%= @product.category.name_ru %>
</p>
<div>
    <%= link_to 'Back to list', admin_products_path %>
</div>

app/views/categories/show.html.erb
<h1><%= t '.all_products_in_category' %> "<%= @category.send("name_" + "#{I18n.locale}") %>"</h1><br>
<div class="row">
	<% @category.products.each do |product| %>
		<div class="col-md-4" align="center">
			<h3><%= product.send("title_" + "#{I18n.locale}") %></h3>
			<%= image_tag("/uploads/#{product.id}", size: '300') %>
			<p> <%= product.send("description_" + "#{I18n.locale}") %></p>
			<p><%= product.price %></p>
		</div>
	<% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop Admin</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/admin/navbar' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/admin/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shop Admin', admin_products_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Products', admin_products_path %></li>
        <li><%= link_to 'Categories', admin_categories_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'View shop', root_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/application/navbar' %>

<div class="container">

  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "alert alert-#{type}" %>
  <% end %>

  <%= yield %>

</div>
</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shop', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- Pages links -->
        <li><%= link_to_unless_current "EN", locale: 'en' %></li>
        <li><%= link_to_unless_current "RU", locale: 'ru' %></li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
             <%= t 'logged_in_as' %> <%= current_user.name %> <%= image_tag(current_user.avatar.url(:thumb)) %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t 'navbar_dropdown' %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if current_user.admin? %>
                  <li><%= link_to (t 'dropdown_menu_admin_panel'), admin_root_path %></li>
                <% end %>
                <li><%= link_to (t 'dropdown_menu_edit_profile'), edit_user_registration_path(current_user, locale: I18n.locale) %></li>
                <li><%= link_to (t 'dropdown_menu_view_orders'), '#' %></li>
                <li class="divider"></li>
                <li><%= link_to (t 'dropdown_menu_sign_out'), destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to (t 'sign_up'), new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to (t 'log_in'), new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/products/index.html.erb
<div class="jumbotron">
  <h1><%= t '.greeting_panel_caption' %></h1>
  <p><%= t '.greeting_panel_text' %></p>
  <p><a href="#" class="btn btn-primary btn-lg"><%= t '.greeting_panel_button' %></a></p>
</div>

<div class="row">

  <div class="col-sm-3">
    <div class="panel panel-default" id="cart">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t 'products.index.list_of_categories' %></h3>
      </div>
      <div class="panel-body">
        <ul>
        <% Category.all.each do |category| %>
            <li><%= link_to category.send("name_" + "#{I18n.locale}"), category_path(category.id) %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="row">
      <div class="col-sm-12 products-pagination">
        <%= will_paginate @products %>
      </div>
    </div>

    <div class="row">
        <% @products.each do |product| %>

        <div class="col-sm-6 product-item">
          <div class="panel panel-default">
            <div class="panel-body">
              <h3><%= product.send("title_" + "#{I18n.locale}") %></h3>
              <div class="img" style="background-image: url('<%= product.image.url(:medium) %>');"></div>
              <h4>$<%= product.price %></h4>
              <p>
                <%= link_to (t '.view_item'), product_path(product), class: "btn btn-success" %></button>
                <button class="btn btn-primary"><%= t '.add_item_to_cart' %></button>
              </p>
            </div>
          </div>
        </div>

        <% end %>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= will_paginate @products %>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
      <div class="panel panel-default" id="cart">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t '.list_of_cart' %></h3>
        </div>
        <div class="panel-body">
          <%= t '.cart_is_empty' %>
        </div>
      </div>
  </div>
</div>

app/views/products/show.html.erb
<h1><%= @product.send("title_" + "#{I18n.locale}") %></h1>
<%= image_tag(@product.image.url(:medium)) %>
<p><%= @product.send("description_" + "#{I18n.locale}") %></p>
<p>
    <%= t '.price_for_product' %> <b><%= @product.price %></b>
</p>
<p>
    <b><%= t ".category" %>: </b> <%= @product.category.send("name_" + "#{I18n.locale}") %>
</p>
<div>
    <%= link_to (t '.back_to_list_link'), root_path %>
</div>

app/views/shared/_field_errors.html.erb
<% if object.errors[field_name].any? %>
    <ul class="error-messages">
      <% object.errors.full_messages_for(field_name).each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
<% end %>